"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FundRaiserCategory = exports.FundRaiserFileType = void 0;
var FundRaiserFileType;
(function (FundRaiserFileType) {
    FundRaiserFileType["Document"] = "Document";
    FundRaiserFileType["Pictures"] = "Pictures";
})(FundRaiserFileType || (exports.FundRaiserFileType = FundRaiserFileType = {}));
var FundRaiserCategory;
(function (FundRaiserCategory) {
    FundRaiserCategory["Education"] = "Education";
    FundRaiserCategory["MedicalAndHealth"] = "Medical and Health";
    FundRaiserCategory["DisasterRelief"] = "Disaster Relief";
    FundRaiserCategory["NonprofitOrganizations"] = "Nonprofit Organizations";
    FundRaiserCategory["CommunityProjects"] = "Community Projects";
    FundRaiserCategory["SportsAndRecreation"] = "Sports and Recreation";
    FundRaiserCategory["ArtsAndCulture"] = "Arts and Culture";
    FundRaiserCategory["AnimalWelfare"] = "Animal Welfare";
    FundRaiserCategory["EnvironmentalCauses"] = "Environmental Causes";
    FundRaiserCategory["ReligiousInitiatives"] = "Religious Initiatives";
    FundRaiserCategory["SocialJustice"] = "Social Justice";
    FundRaiserCategory["ScienceAndResearch"] = "Science and Research";
    FundRaiserCategory["EntrepreneurshipAndInnovation"] = "Entrepreneurship and Innovation";
    FundRaiserCategory["MemorialsAndFunerals"] = "Memorials and Funerals";
    FundRaiserCategory["PersonalEmergencies"] = "Personal Emergencies";
    FundRaiserCategory["TravelAndAdventure"] = "Travel and Adventure";
    FundRaiserCategory["EventsAndCelebrations"] = "Events and Celebrations";
    FundRaiserCategory["YouthPrograms"] = "Youth Programs";
    FundRaiserCategory["VeteransAndMilitary"] = "Veterans and Military";
    FundRaiserCategory["HungerAndPoverty"] = "Hunger and Poverty";
    FundRaiserCategory["HousingAndHomelessness"] = "Housing and Homelessness";
    FundRaiserCategory["HumanRights"] = "Human Rights";
    FundRaiserCategory["EducationScholarships"] = "Education Scholarships";
    FundRaiserCategory["SeniorCitizens"] = "Senior Citizens";
    FundRaiserCategory["CrisisSupport"] = "Crisis Support";
    FundRaiserCategory["MentalHealth"] = "Mental Health";
    FundRaiserCategory["TechnologyAndGadgets"] = "Technology and Gadgets";
    FundRaiserCategory["CreativeProjects"] = "Creative Projects";
    FundRaiserCategory["LegalDefense"] = "Legal Defense";
    FundRaiserCategory["InternationalAid"] = "International Aid";
})(FundRaiserCategory || (exports.FundRaiserCategory = FundRaiserCategory = {}));
